version: '3.7'
services:
  server:
    ports:
      - "8080:8080"
    container_name: crud-container
    image: crud
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
  db:
    ports:
      - '3306:3306'
    container_name: mysql01
    environment:
      - MYSQL_DATABASE=bdejemplo
      - MYSQL_ROOT_PASSWORD=root
    image: mysql  
  

